Rox migrations
roge530/BeduBackend pull request #14
Opened 2022-11-10 06:10 UTC by rxha

migrations implementation// proyect was running locally on mysql

2022-11-10 14:14 UTC, roge530 requested changes
La migración no esta configurada para postgresql sino para mysql, no se modifica el comportamiento de .env.example para adaptarlo a entornos como muestra la documentación, no veo la adición de los seeders

2022-11-10 14:23 UTC, rxha commented
> La migración no esta configurada para postgresql sino para mysql, no se modifica el comportamiento de .env.example para adaptarlo a entornos como muestra la documentación, no veo la adición de los seeders

En la especificacion del proyecto, Andres menciono que el proyecto debia correr con Mysql

2022-11-10 14:43 UTC, roge530 commented
> En la especificacion del proyecto, Andres menciono que el proyecto debia correr con Mysql

Vale entonces solo queda integrar los seeders y la nueva configuración para .env.example

2022-11-10 16:19 UTC, rxha commented
> > En la especificacion del proyecto, Andres menciono que el proyecto debia correr con Mysql
> 
> Vale entonces solo queda integrar los seeders y la nueva configuración para .env.example

Con la nueva conf para .env.example, te refieres a que coincida con .env? Añado los seeders

2022-11-10 23:06 UTC, roge530 commented
> Con la nueva conf para .env.example, te refieres a que coincida con .env? Añado los seeders

el .env.example para usar mysql

https://stackoverflow.com/questions/45790759/sequalize-migration-with-dotenv

este enlace te explica una parte de como configurar la migracion de sequelize con .env

https://sequelize.org/docs/v6/other-topics/migrations/#dynamic-configuration

2022-11-11 01:09 UTC, roge530 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Integrar las migraciones](https://trello.com/c/tN0pIomb/27-integrar-las-migraciones)

2022-11-13 05:07 UTC, roge530 commented
Resolvere los conflictos de merge,  excelente adicion de los seeders

2022-11-13 05:14 UTC, roge530 approved these changes

2022-11-13 05:14 UTC, merged

2022-11-13 05:19 UTC, rxha commented
> Resolvere los conflictos de merge, excelente adicion de los seeders

FYI. Tuve un conflicto a la hora de ejecutar las migraciones y los seeders, ya que necesitan ser del tipo commonjs y nosotros trabajamos todo como modulos, existe ese mismo problema para el archivo de config.js. La solucion que encontramos fue que en la carpeta de migrations y de seeders se sobreescriba el type de los archivos . Para hacer las pruebas hice lo mismo con el archivo de config.js que usa sequelize para ejecutar las migraciones/seeders.

2022-11-13 05:21 UTC, roge530 commented
> FYI. Tuve un conflicto a la hora de ejecutar las migraciones y los seeders, ya que necesitan ser del tipo commonjs y nosotros trabajamos todo como modulos, existe ese mismo problema para el archivo de config.js. La solucion que encontramos fue que en la carpeta de migrations y de seeders se sobreescriba el type de los archivos . Para hacer las pruebas hice lo mismo con el archivo de config.js que usa sequelize para ejecutar las migraciones/seeders.

Si, estoy trabajando en la adaptación